# Generated by Django 3.2.7 on 2021-09-11 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_album_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.category'),
        ),
    ]
