# Generated by Django 3.2.7 on 2021-09-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default='playlists/covers/default.png', upload_to='playlists/covers'),
        ),
    ]
