# Generated by Django 3.2.7 on 2021-09-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210911_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='background_image',
            field=models.ImageField(default='artists/backgrounds/default.png', upload_to='artists/backgrounds'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='artists/covers/default.png', upload_to='artists/covers'),
        ),
    ]
