# Generated by Django 3.2.7 on 2021-09-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_rename_musics_favourite_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='is_fav',
            field=models.BooleanField(default=True),
        ),
    ]
