# Generated by Django 3.2.7 on 2021-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20210912_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='image',
            field=models.ImageField(default='favourite/images/default.png', upload_to='favourite/images'),
        ),
    ]
