# Generated by Django 3.2.7 on 2021-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_favourite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='is_fav',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='music',
        ),
        migrations.AddField(
            model_name='favourite',
            name='musics',
            field=models.ManyToManyField(related_name='is_fav', to='music.Music'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='image',
            field=models.ImageField(default='favourite/images/default.png', upload_to=''),
        ),
    ]
