# Generated by Django 3.2.7 on 2021-09-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20210913_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(related_name='music', to='music.Artist'),
        ),
    ]
